Quark-Engine integration
Surendrajat/APKLab pull request #92
Opened 2021-01-20 09:06 UTC by pulorsok

# Quark-Engine integration

### Requirements:

 - Python 3.7+
 - Quark-Engine 21.01.3+

### Add "Quark Analysis" option

Add "Quark Analysis" as one of the "decode quick pick" items.

Then Quark will be executed after the decompilation of Jadx. And the report will appear as a JSON file in the decoded directory.

![](https://i.imgur.com/p13G4tV.gif)

### A warning message pops up when Quark is not installed
When "Quark Analysis" is selected, it will first check whether Quark-Engine has been installed. If not, it will show an error message and exit the process.

![](https://i.imgur.com/OkehC2T.png)

### Show report as WebView

The summary report of the APK will be shown as a WebView at the bottom panel.

You can also right-click the report file to show the WebView (summary report).

![](https://i.imgur.com/fH5oCvk.png)

Righ-click quark report file to show WebView (summary report).

![](https://i.imgur.com/NQTITYa.gif)

### Source Code Navigation

In WebView (summary report), click on the description of potential malicious activities, the editor panel will open the exact .smali file and highlight the whole block of the function where the activities are detected.

Note: 
Meaning of colors in the highlighted smali codes.
- Green: The whole block of function.
- Yellow: Where the native APIs are called. 

![](https://i.imgur.com/u8CpOx8.gif)

2021-01-20 15:22 UTC, Surendrajat commented on src/extension.ts
> +            updateTools()
I think this can be removed as `quark` does not depened on these tools for analysis. Simple call it like `apklab.patchApkForHttps`

2021-01-20 15:38 UTC, Surendrajat requested changes
Hi @pulorsok, thanks for the PR. Looking great overall. Just adding small comments here and there.

2021-01-20 15:38 UTC, Surendrajat commented on src/quark-tools.ts
> +        const cmd = `cd ~/ && quark`;
It won't work in windows. Maybe just call `quark` instead?

2021-01-20 15:38 UTC, Surendrajat commented on src/quark-tools.ts
> +     * Analyzing APK useing Quark-Engine.
using

2021-01-20 15:38 UTC, Surendrajat commented on src/quark-tools.ts
> +                        if (error) {
Showing logs in outputchannel can be useful during analyzing. Not sure if quark spits some useful logs.

2021-01-20 15:38 UTC, Surendrajat commented on src/quark-tools.ts
> +                        if (!quark.killed) {
It will only be useful if user can somehow cancel the request. You can show a progress notification like decode/decompile process with a cancel button.

2021-01-20 15:38 UTC, Surendrajat commented on src/quark-tools.ts
> +        @import 'https://fonts.googleapis.com/css?family=Montserrat:300,400,700';
Can we use some non-goolge fonts maybe? :) Not a issue, just in case.

2021-01-20 15:39 UTC, Surendrajat commented on src/extension.ts
> +            updateTools()
I think this can be removed as `quark` does not depend on these tools for analysis. Simple call it like `apklab.patchApkForHttps`

2021-01-20 15:55 UTC, Surendrajat commented on src/quark-tools.ts
> +    let srcPath = "/smali/" + func.class + ".smali";
It won't work with muti-dex apk where smali code is spit into `smali`, `smali_classes2`... dirs.

2021-01-21 07:44 UTC, amsharma44 requested changes
Thank for the PR @pulorsok. Awesome work, just a minor concern I have.

2021-01-21 10:29 UTC, pulorsok commented on src/quark-tools.ts
> +        const cmd = `cd ~/ && quark`;
Quark-Engine will write a log file when executed.
To prevent the log file from being written at the root directory, 
I use the command `cd ~/` before `quark`

Not sure if Windows have the same problem.
But I will add a function to check OS platform,
and use a different command for each platform.

2021-01-21 10:30 UTC, pulorsok commented on src/quark-tools.ts
> +        @import 'https://fonts.googleapis.com/css?family=Montserrat:300,400,700';
Sure, I will fix it.

2021-01-21 10:30 UTC, pulorsok commented on src/extension.ts
> +            updateTools()
You're right, 
I didn't notice that, will fix it too.

2021-01-21 10:30 UTC, pulorsok commented
@Surendrajat @amsharma44 
Thank you for the comments, I will fix these issues ASAP.

And there are still a few works I will do after.
- Prettier quark report style on WebView :
I will make the report WebView more pretty and readable.

- Quark test unit :
The test unit will be finished next week.

- Same malicious activity in multiple smali files :
Sometime, the same malicious activity will be detected in several smali files.
However, source code navigation will open only a file to show where the activity is.
I will figure out a way to fix this issue (maybe add a hoover to let the user choose which file to open).

2021-01-21 15:59 UTC, Surendrajat commented on src/quark-tools.ts
> +        const quarkRulePath = path.join(apkDecodedDir, "quark-rules/");
After https://github.com/quark-engine/quark-engine/pull/107, this won't work and can be removed. Failure logs: https://del.dog/gijimobife.txt

2021-01-25 10:56 UTC, Surendrajat commented
@pulorsok please this PR rebase on master.

2021-01-25 11:37 UTC, pulorsok commented
Hi @Surendrajat ,
I fixed the problem you mentioned and added a test unit for quark analysis.
I also improved the Webview quark report to get a better UI.
Now it can display multiple functions where the activity is located.

Click on the description of the potentially malicious activity, it will expand and show the detailed of the function (green box), including the class name, method name and smali code that executes the API.
Click on the green box and it will navigate to the source code file.

![](https://i.imgur.com/r8lMKM9.gif)

2021-01-25 12:17 UTC, Surendrajat commented on src/quark-tools.ts
> +        const cmd = `cd ~/ && quark`;
@pulorsok no need to `cd` at all now. `quark` now writes logs in `~/.quark-engine/`

2021-01-25 12:20 UTC, Surendrajat commented
@pulorsok Thanks for update. Please check the [recent changes on `quark` side](https://github.com/quark-engine/quark-engine/compare/v21.01.3...master) as well.

2021-01-25 12:34 UTC, Surendrajat requested changes
@pulorsok Leaving some comments here. Mostly related to new `quark-engine` changes.

2021-01-25 12:34 UTC, Surendrajat commented on src/common.ts
> +export const quarkDataDirPath = path.join(apklabDataDir, "quarkDataDir");
This won't be needed once new `quark-engine` is released.

2021-01-25 12:34 UTC, Surendrajat commented on src/quark-tools.ts
> +    outputChannel.appendLine(`Search smali file: ${func.class}`);
```suggestion
    outputChannel.appendLine(`Searching smali file: ${func.class}`);
```

2021-01-25 12:34 UTC, Surendrajat commented on src/quark-tools.ts
> +            : `cd ${String(quarkDataDirPath)} && quark`;
I meant to remove `cd` entirely :)
You will no longer need it anyway as the logs will go in `~/.quark-engine`.

2021-01-25 12:34 UTC, Surendrajat commented on src/quark-tools.ts
> +            outputChannel.appendLine(`Catched error from Quark install check`);
```suggestion
            outputChannel.appendLine(`Caught error from Quark install check`);
```

2021-01-25 12:34 UTC, Surendrajat commented on src/quark-tools.ts
> +        const quarkRulePath = path.join(quarkDataDirPath, "quark-rules/");
This can be safely removed now :)

2021-01-25 12:34 UTC, Surendrajat commented on src/quark-tools.ts
> +        const script = `cd ${quarkDataDirPath} && quark -a ${apkFilePath} -r ${quarkRulePath} -o ${reportPath}`;
Same here. Since logs and rules will go in `~/.quark-engine` by default we don't need to do `cd` or to pass `-r`.
```suggestion
        const script = `quark -a ${apkFilePath} -o ${reportPath}`;
```

2021-01-25 12:34 UTC, Surendrajat commented on src/quark_html.ts
> +            // acitivity = report[pkey.split("-")[0]]["crime"];
```suggestion
```

2021-01-25 12:34 UTC, Surendrajat commented on src/test/suite/extension.test.ts
> +        const jsonFilePath = path.join(simpleKeyboardDir, "decoded_files.json");
No need to check `decoded_files.json` in this test. Please check `qurark_report.json` directly.

2021-01-25 14:33 UTC, Surendrajat commented
@pulorsok could you please rebase it once again? Seems like some conflicts with master again.

2021-01-26 09:18 UTC, amsharma44 approved these changes

2021-01-26 10:57 UTC, Surendrajat commented
@pulorsok I tested the changes, and it seems we are almost there :)

There are few things that need further changes:
1. The https://github.com/Surendrajat/apklab-testdata submodule needs update to fix the tests.
2. Resulting WebView needs some tweaks. See this:
https://user-images.githubusercontent.com/11215000/105835087-5bfd0e00-5ff1-11eb-846f-565b50490848.mp4

My concerns here are:
- The WebView opens in upper-half and not in lower half which is not intuitive (maybe open it in full).
- The space between `POTENTIAL MALICIOUS ACTIVITIES` and `CONFIDENCE` is a lot.
- The WebView expands out of the TextEditor view (because of above space, I guess).

2021-01-27 10:21 UTC, Surendrajat commented
@pulorsok I've added the missing step from GitHub workflow to install `quark-egnine` before tests. Please pull the changes and rebase on master once. It should fix the tests.

2021-01-28 06:53 UTC, Surendrajat commented on src/test/suite/extension.test.ts
> +    it("Decode SimpleKeyboard.apk", async function () {
```suggestion
    it("Quark-engine Analysis", async function () {
```

2021-01-28 07:09 UTC, Surendrajat commented on src/test/suite/extension.test.ts
> +        console.log("Comparing file list...");
```suggestion
        console.log("Comparing analysis report...");
```

2021-01-28 08:57 UTC, Surendrajat approved these changes
@pulorsok Great job!
Looks good overall. I'm planning to move docs to a proper repo, so we can add more .gifs and guide there.
Thanks again for your contribution. Thanks, @krnick, for promptly handling issues with integration and @18z, for reaching out to me :D

2021-01-28 09:09 UTC, merged